# Generated by Django 3.1.7 on 2021-03-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210325_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cooktime',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.CharField(default='hello', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.CharField(default='hello', max_length=800),
            preserve_default=False,
        ),
    ]
