# Generated by Django 3.1.7 on 2021-03-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210326_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='instructions',
            field=models.TextField(max_length=800),
        ),
    ]
